### ISSUE TITLE
webio lab extension install yields error from jupyter_notebook_config.py (on Windows)

### ISSUE THREAD

**Issue by standarddeviant** [JuliaGizmos/WebIO.jl#142]
Hello,

I was playing around with Interact.jl and following their tutorial from here
https://juliagizmos.github.io/Interact.jl/latest/tutorial.html#Tutorial-1

I ran the jupyterlab extension install and re-started juypyter-lab.  Then I see this error
```md
C:\Users\dave>jupyter lab
[E 13:29:23.161 LabApp] Exception while loading config file C:\Users\dave\.jupyter\jupyter_notebook_config.py
    Traceback (most recent call last):
      File "C:\Users\dave\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "C:\Users\dave\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "C:\Users\dave\AppData\Local\Continuum\anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "C:\Users\dave\AppData\Local\Continuum\anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "C:\Users\dave\.jupyter\jupyter_notebook_config.py", line 608
        if os.path.isfile("C:\Users\dave\.julia\v0.6\WebIO\deps\jlstaticserve.py"):
                         ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[I 13:29:25.356 LabApp] JupyterLab beta preview extension loaded from C:\Users\dave\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab
[I 13:29:25.357 LabApp] JupyterLab application directory is C:\Users\dave\AppData\Local\Continuum\anaconda3\share\jupyter\lab
[I 13:29:25.934 LabApp] Serving notebooks from local directory: C:\Users\dave
[I 13:29:25.935 LabApp] 0 active kernels
[I 13:29:25.937 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 13:29:25.937 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 13:29:28.119 LabApp] > C:\Users\dave\AppData\Local\Continuum\anaconda3\npm.CMD pack C:\Users\dave\.julia\v0.6\WebIO\assets\webio
julia-web-io-0.1.0.tgz
[I 13:29:31.145 LabApp] Build is up to date
```

Here's the python code that WebIO added to `C:\Users\dave\.jupyter\jupyter_notebook_config.py`
```python
import sys, os
if os.path.isfile("C:\Users\dave\.julia\v0.6\WebIO\deps\jlstaticserve.py"):
    sys.path.append("C:\Users\dave\.julia\v0.6\WebIO\deps")
    c = get_config()
    c.NotebookApp.nbserver_extensions = {
        "jlstaticserve": True
    }
else:
    print("WebIO config in ~/.jupyter/jupyter_notebook_config.py but WebIO plugin not found")
###JULIA-WEBIO-CONFIG-END
```

The problem is that those backslashes (I know, I know...) aren't escaped.  A simple solution is to change the generated python code to the following:
```python
import sys, os
if os.path.isfile(r"C:\Users\dave\.julia\v0.6\WebIO\deps\jlstaticserve.py"):
    sys.path.append(r"C:\Users\dave\.julia\v0.6\WebIO\deps")
    c = get_config()
    c.NotebookApp.nbserver_extensions = {
        "jlstaticserve": True
    }
else:
    print("WebIO config in ~/.jupyter/jupyter_notebook_config.py but WebIO plugin not found")
###JULIA-WEBIO-CONFIG-END
```

This makes both of those paths "raw strings" where a single backslash character actually means a single backslash character.

**Comment by rdeits** [comment]
Good catch! Would you be willing to make a PR? The relevant code is generated here: https://github.com/JuliaGizmos/WebIO.jl/blob/master/deps/build.jl

**Comment by shashi** [comment]
`r""` has some small problem
```python
>>> r"foo\"
  File "<stdin>", line 1
    r"foo\"
          ^
SyntaxError: EOL while scanning string literal
```

I think one fix would be to use `JSON.json(path)` instead of just `path`.

**Comment by shashi** [comment]
Fixed by https://github.com/JuliaGizmos/WebIO.jl/commit/a6f1d663ce88c21f1a8f5cd8d85bf05232553914 thanks to @SimonDanisch
