### ISSUE TITLE
no output on MacOS

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/WebIO.jl#160]
I am using Jupyter on MacOS (in Chrome) and getting no output. 

If I run

```julia
using WebIO
display(Node(:input, attributes = Dict("type" => "range")))
```
nothing appears.

```julia
Pkg.status("WebIO")
 - WebIO                         0.2.4
```

```julia
versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by SimonDanisch** [comment]
I think I can reproduce and see errors in the console:
![grafik](https://user-images.githubusercontent.com/1010467/43107463-6a75a88a-8edd-11e8-9031-70e61653b432.png)

**Comment by SimonDanisch** [comment]
Hm, I tried 0.2.2 up to master and it all didn't work^^ Also 0.2.5 + 0.2.6 seem to be unknown to metadata?!
Anything I'm missing, or has the IJulia support been broken for a long time now? ;)

**Comment by AshtonSBradley** [comment]
ah, yes, that would be consistent with an issue I opened on InteractNext.jl a while back ( I didn't realise that everything had moved over to InteractBase)

**Comment by AshtonSBradley** [comment]
I am happy to try this. Just to check - should I be clearing .julia first, or can I initialise a package repository somewhere else?

**Comment by rdeits** [comment]
No, you don't need to clear out `.julia`. To make a nice clean package directory, you can do the following: 

* (in your terminal, make a new temporary directory and `cd` into it
* Create a new package folder with `mkdir packages` 
* Tell Julia to use it by setting the environment variable with `export JULIA_PKGDIR=`pwd`/packages`
* Start Julia
* `julia> Pkg.init()`
* `julia> Pkg.add("IJulia")`
* etc.

Julia will use that package directory whenever it's launched from a terminal with the `export JULIA_PKGDIR=...` set.

**Comment by AshtonSBradley** [comment]
I tried that, but then julia wouldn't finish executing even basic commands (cells just have a * but don't finish).

**Comment by rdeits** [comment]
Maybe you have a very old version of `jupyter` installed? Can you try repeating the above steps, but before you do `Pkg.init()`, can you also run (in your terminal, not Julia)

```
export PYTHON=""
export JUPYTER=""
```

**Comment by dpsanders** [comment]
I don't get any output either for the `Node` test, using WebIO 0.2.4 on MacOS with Jupyter notebook version 5.4.1, on Chrome.

**Comment by AshtonSBradley** [comment]
ok, I did the new steps, no change.

**Comment by AshtonSBradley** [comment]
![screen shot 2018-07-23 at 8 10 58 pm](https://user-images.githubusercontent.com/24194258/43114564-922dd128-8eb4-11e8-8f76-bce577d4a1a1.png)

**Comment by AshtonSBradley** [comment]
```julia

2 required packages:
 - IJulia                        1.9.0
 - WebIO                         0.2.4
16 additional packages:
 - AssetRegistry                 0.0.2
 - BinDeps                       0.8.8
 - BinaryProvider                0.3.3
 - Compat                        1.0.0
 - Conda                         0.8.1
 - FunctionalCollections         0.3.2
 - JSON                          0.17.2
 - MbedTLS                       0.5.12
 - Nullables                     0.0.6
 - Observables                   0.1.2
 - Pidfile                       1.0.0
 - Requires                      0.4.4
 - SHA                           0.5.7
 - URIParser                     0.3.1
 - VersionParsing                1.1.1
 - ZMQ                           0.6.2
```

**Comment by rdeits** [comment]
What are the contents of your `~/.jupyter/jupyter_notebook_config.py` file?

**Comment by AshtonSBradley** [comment]
```python
###JULIA-WEBIO-CONFIG-BEGIN
import sys, os
if os.path.isfile("/Users/abradley/packages/v0.6/WebIO/deps/jlstaticserve.py"):
    sys.path.append("/Users/abradley/packages/v0.6/WebIO/deps")
    c = get_config()
    c.NotebookApp.nbserver_extensions = {
        "jlstaticserve": True
    }
else:
    print("WebIO config in ~/.jupyter/jupyter_notebook_config.py but WebIO plugin not found")
###JULIA-WEBIO-CONFIG-END
```

**Comment by rdeits** [comment]
ok, that looks fine. Let me pull out my old mac and give it a try...

**Comment by rdeits** [comment]
Ok, yeah, I can reproduce the error on a totally clean OSX package installation.

**Comment by rdeits** [comment]
Ok, figured it out. Try running `jupyter notebook` from your terminal. When I do that, the first thing that's printed is a warning message: 

```
[W 00:11:37.798 NotebookApp] Collisions detected in /Users/rdeits/.jupyter/jupyter_notebook_config.py and /Users/rdeits/.jupyter/jupyter_notebook_config.json config files. /Users/rdeits/.jupyter/jupyter_notebook_config.json has higher priority: {
      "NotebookApp": {
        "nbserver_extensions": "{'jlstaticserve': True} ignored, using {'jupyterlab': True}"
      }
    }
```

That warning is important: it means that the Jupyter `.json` configuration file is taking priority of the Jupyter `.py` configuration file. But WebIO uses that `.py` config file to load the server-side extensions that it needs. 

If you see the same warning, please try: 

```sh
mv ~/.jupyter/jupyter_notebook_config.json ~/.jupyter/jupyter_notebook_config.backup.json
jupyter notebook
```

(you need to re-launch `jupyter notebook` after doing this, since we need to restart the jupyter server itself). 

Doing those two steps fixed WebIO on my mac.

**Comment by SimonDanisch** [comment]
On windows, I actually get this:
```Julia
julia> run(Cmd(IJulia.notebook_cmd))
WebIO config in ~/.jupyter/jupyter_notebook_config.py but WebIO plugin not found
[I 11:15:56.282 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\sdani\.julia\v0.6\Conda\deps\usr\lib\site-packages\jupyterlab
[I 11:15:56.292 NotebookApp] JupyterLab application directory is C:\Users\sdani\.julia\v0.6\Conda\deps\usr\share\jupyter\lab
```

**Comment by SimonDanisch** [comment]
Ah, the paths were all not propperly escaped....
Now I get:
```Julia
julia> run(Cmd(IJulia.notebook_cmd))
[W 11:17:49.275 NotebookApp] Error loading server extension jlstaticserve
    Traceback (most recent call last):
      File "C:\Users\sdani\.julia\v0.6\Conda\deps\usr\lib\site-packages\notebook\notebookapp.py", line 1481, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\sdani\.julia\v0.6\Conda\deps\usr\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
    ImportError: No module named jlstaticserve
[I 11:17:49.309 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\sdani\.julia\v0.6\Conda\deps\usr\lib\site-packages\jupyterlab
[I 11:17:49.309 NotebookApp] JupyterLab application directory is C:\Users\sdani\.julia\v0.6\Conda\deps\usr\share\jupyter\lab
```

**Comment by AshtonSBradley** [comment]
This fixed my fresh package install, but now I tried it for my usual Julia package directory, and the problem is not fixed

**Comment by SimonDanisch** [comment]
Well, windows still doesn't work, so I guess there are still other issues hiding ;)

**Comment by shashi** [comment]
Could you try #162 after moving the backed up json file back to its original location?

`mv ~/.jupyter/jupyter_notebook_config.backup.json ~/.jupyter/jupyter_notebook_config.json`

and see if `Pkg.build("WebIO")` on that branch fixes?

**Comment by SimonDanisch** [comment]
Just came here to complain that you ignored the windows problem, but it is actually working now :) 
![grafik](https://user-images.githubusercontent.com/1010467/43194013-b47c1e8a-9001-11e8-9f4d-f95b8417f210.png)

Thanks @shashi  :)
