### ISSUE TITLE
Wrong instruction for jupyterlab in README.md

### ISSUE THREAD

**Issue by xukai92** [JuliaGizmos/WebIO.jl#278]
```
cd(Pkg.dir("WebIO", "assets"))
```

should be

```
cd(Pkg.dir("WebIO", "packages"))
```

Also it would be useful to mention that TypeScript is required in npm.

**Comment by xukai92** [comment]
I got the following error message

```
ValueError: "/Users/kai/.julia/packages/WebIO/7G1ZY/packages/webio" is not a valid extension:
No `jupyterlab` key
```

**Comment by travigd** [comment]
We need to publish the latest version of the jupyter labextension to npm so you can just run `jupyter labextension install @webio/jupyter-lab-provider`.

**Comment by vilim** [comment]
What is the status of publishing the latest version to npm? When trying to follow instructions at
https://github.com/JuliaGizmos/WebIO.jl/tree/master/packages/jupyter-lab-provider
I get:
```
(base) PS>jupyter-labextension install C:\Users\vilim\.julia\packages\WebIO\7G1ZY\packages\jupyter-lab-provider
Node v9.6.1

> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\vilim\.julia\packages\WebIO\7G1ZY\packages\jupyter-lab-provider
webio-jupyter-lab-provider-1.0.2.tgz
Node v9.6.1

> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\vilim\.julia\packages\WebIO\7G1ZY\packages\jupyter-lab-provider
webio-jupyter-lab-provider-1.0.2.tgz
> "C:\Program Files\nodejs\npm.CMD" pack C:\Users\vilim\.julia\packages\WebIO\7G1ZY\packages\webio

> @webio/webio@1.0.2 prepack C:/Users/vilim/.julia/packages/WebIO/7G1ZY/packages/webio
> npm run build


> @webio/webio@1.0.2 build C:\Users\vilim\.julia\packages\WebIO\7G1ZY\packages\webio
> tsc -p .

webio-webio-1.0.2.tgz
> node C:\Users\vilim\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @jupyterlab/application > @jupyterlab/apputils > react > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning @jupyterlab/plotly-extension > plotly.js > mapbox-gl > @mapbox/gl-matrix@0.0.1: This
warning @jupyterlab/plotly-extension > plotly.js > regl-splom > left-pad@1.3.0: use String.prototype.padStart()
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
error Package "" refers to a non-existing file '"C:\\Users\\vilim\\AppData\\Local\\Yarn\\Cache\\v2\\.tmp\\webio"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node C:\Users\vilim\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build
yarn run v1.9.4
$ webpack
C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:74
                                throw err;
                                ^

Error: Cannot find module '@webio\jupyter-lab-provider\package.json'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.resolve (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:166:23)
    at C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:29:45
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:28:22)
    at Object.<anonymous> (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\webpack.config.js:20:7)
    at Module._compile (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:115:13)
    at requireConfig (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:117:6)
    at C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\utils\convert-argv.js:122:15)
    at yargs.parse (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\yargs\yargs.js:567:18)
    at C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:375:3)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\vilim\anaconda3\share\jupyter\lab\staging\node_modules\webpack\bin\webpack.js:157:2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(base) PS>
```

**Comment by alecloudenback** [comment]
Before the npm package is published is there a way to get WebIO to work with JupyterLab? I get the error `WebIO not detected.` using Julia 1.1.0, and WebIO v0.8.1

![image](https://user-images.githubusercontent.com/711879/58067150-f127de00-7b51-11e9-9c18-d6d1b22bcf30.png)

**Comment by travigd** [comment]
I plan to tackle this soon, possibly without using a separate npm repository.

For now, try running `jupyter labextension install ~/.Julia/packages/WebIO/xxxxx/packages/jupyter-lab-provider` where `xxxxx` is the slug for the installed version of WebIO.

Part of the difficulty is that in a lot of situations, we don't know where Jupyter (the exe) lives, so we just write to config paths. But Jupyter lab incorporates all the JS code into one big glob (so our extension code lives in the same bundled file as the core code) and so has to be installed using the labextension command (as far as I know, anyway). So it's always going to be a little bit trickier.

**Comment by vilim** [comment]
This command (`jupyter labextension install ~/.Julia/packages/WebIO/xxxxx/packages/jupyter-lab-provider`) is the one I put above and have got the error (WebIO 0.8.1)

**Comment by alecloudenback** [comment]
I'm not well versed in non-basic Julia package authoring, but would it be possible to include a [command to run](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring) `jupyter labextension install` in the `jupyter-lab-provider` directory when building the package? I [asked in #helpdesk](https://julialang.slack.com/archives/C6A044SQH/p1558496756046100) if this is doable, I could also ask on Discourse.

**Comment by travigd** [comment]
@alexcloudenback It's easy to run that command but Jupyter is frequently not in the users path (e.g. if installed with Conda.jl) or users might have multiple Jupyters (e.g. in separate python virtual environments). I plan to try to implement that soon though.

**Comment by dav2017** [comment]
I followed the instructions, runnig (from REPL):
```
Pkg.clone("https://github.com/shashi/WebIO.jl.git")
Pkg.build("WebIO")
```
Then from bash shell (as superuser):
```
cd .julia/dev/WebIO/packages
jupyter labextension install jupyter-lab-provider
```
but I get the following error:

warning @jupyterlab/terminal-extension > @jupyterlab/apputils > react > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
error Package "" refers to a non-existing file '"/usr/local/share/.cache/yarn/v2/.tmp/webio"'.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
\> node /usr/local/lib/python3.5/dist-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

Error: Cannot find module '@webio/jupyter-lab-provider/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (/home/local/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at /home/local/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:29:45
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (/home/local/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/build.js:28:22)
    at Object.<anonymous> (/home/local/share/jupyter/lab/staging/webpack.config.js:20:7)
    at Module._compile (/home/local/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/home/local/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:115:13)
    at requireConfig (/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:117:6)
    at /home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/utils/convert-argv.js:122:15)
    at yargs.parse (/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/local/share/jupyter/lab/staging/node_modules/yargs/yargs.js:567:18)
    at /home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/local/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:375:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/local/share/jupyter/lab/staging/node_modules/webpack/bin/webpack.js:157:2)
error Command failed with exit code 1.

Thanks for any help

**Comment by sschuldenzucker** [comment]
Problems here, too. (Windows 10)

 I had to install `typescript` and `webpack` myself. After doing it, I still get an error:
```
error Package "" refers to a non-existing file '"C:\\Users\\steff\\AppData\\Local\\Yarn\\Cache\\v2\\.tmp\\webio"'.
```

But the process continues. Then I'm asked to install `webpack-cli`, to which I respond with yes. But then I get:
```
npm WARN webpack-cli@3.3.2 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
[...]
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at runCommand.then (C:\ProgramData\Anaconda3\node_modules\webpack\bin\webpack.js:143:5)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
and that's basically it.
