### ISSUE TITLE
WebIO not detected in jupyterlab

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/WebIO.jl#315]
## The bug

When using `Interact.jl` in jupyterlab, specifically `@manipulate`, one gets the message
"WebIO not detected."
and no output is produced. 
<img width="737" alt="Screen Shot 2019-07-01 at 12 19 44 PM" src="https://user-images.githubusercontent.com/24194258/60404195-9e365180-9bfa-11e9-9242-dca0c6e06c4e.png">
## Context

Your context here.
```julia
julia> Pkg.status("WebIO")
    Status `~/.julia/environments/v1.1/Project.toml`
  [0f1e0344] WebIO v0.8.5

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

Using `jupyterlab`. I don't know how to run `jupyter labextension list` for the containerized `jupyterlab` installed by `IJulia`. Possibly I am just missing an extension? 

It works fine in the `jupyter` notebook from `IJulia`.

**Comment by travigd** [comment]
Do you have more than one version of Jupyter Lab (e.g. one on your system and the one installed by IJulia)?

**Comment by AshtonSBradley** [comment]
yes and no: I get the same error on my laptop where I only have `IJula`'s version, and on my desktop where I also installed anaconda to see if that would fix it. If I open Jupiterlab from the terminal using anaconda, same result

**Comment by travigd** [comment]
Can you `Pkg.build("WebIO")` and see if that fixes things? If not, copy the output here?

We try to find the best JupyterLab to use; it defaults to the one in your path and if there is none it tries to use the one IJulia installs (if any).

**Comment by travigd** [comment]
Can you `Pkg.build("WebIO")` and see if that fixes things? If not, copy the output here?

We try to find the best JupyterLab to use; it defaults to the one in your path and if there is none it tries to use the one IJulia installs (if any).

**Comment by AshtonSBradley** [comment]
I get identical result to screenshot above, after (including the jupyterlab() Info so you see which one is run)
```julia
(v1.1) pkg> build WebIO
  Building MbedTLS → `~/.julia/packages/MbedTLS/X4xar/deps/build.log`
  Building WebIO ──→ `~/.julia/packages/WebIO/9qsL8/deps/build.log`

julia> using IJulia
[ Info: Recompiling stale cache file /Users/abradley/.julia/compiled/v1.1/IJulia/nfu7T.ji for IJulia [7073ff75-c697-5162-941a-fcdaad2a7d2a]

julia> jupyterlab()
[ Info: running setenv(`/Users/abradley/.julia/conda/3/bin/jupyter lab`,["XPC_FLAGS=0x0", "VIRTUALENVWRAPPER_PYTHON=/Library/Frameworks/Python.framework/Versions/3.6/bin/python3", "PATH=/Users/abradley/.julia/conda/3/bin:/Applications/OpenSCAD.app/Contents/MacOS/:/Applications/Julia-1.1.app/Contents/Resources/julia/bin/:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/texlive/2016/bin/x86_64-darwin:/Users/abradley/Library/Python/3.6/bin:", "PWD=/Users/abradley", "VIRTUALENVWRAPPER_PROJECT_FILENAME=.project", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "DISPLAY=/private/tmp/com.apple.launchd.kqoUxZCAzq/org.macosforge.xquartz:0", "SHELL=/bin/bash", "VIRTUALENVWRAPPER_SCRIPT=/Users/abradley/Library/Python/3.6/bin/virtualenvwrapper.sh", "__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0", "TMPDIR=/var/folders/3l/7hpnhzns3qgbwvmqzm23bqtc0000gn/T/", "BROWSER=open", "LANG=en_NZ.UTF-8", "SHLVL=0", "LOGNAME=abradley", "TERM_SESSION_ID=C95D59EA-0EB4-4571-BC47-5BE52908AD53", "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.HJBe7By2Bw/Listeners", "VIRTUALENVWRAPPER_WORKON_CD=1", "Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.3WjyJ6GDeZ/Render", "USER=abradley", "VIRTUALENVWRAPPER_HOOK_DIR=/Users/abradley/.virtualenvs", "PROJECT_HOME=/Users/abradley/sites", "TERM=xterm-256color", "HOME=/Users/abradley", "TERM_PROGRAM_VERSION=404.1", "JULIA_NUM_THREADS=8", "WORKON_HOME=/Users/abradley/.virtualenvs", "OPENBLAS_MAIN_FREE=1"])
```

```julia
(v1.1) pkg> status WebIO
    Status `~/.julia/environments/v1.1/Project.toml`
  [0f1e0344] WebIO v0.8.6

(v1.1) pkg> status IJulia
    Status `~/.julia/environments/v1.1/Project.toml`
  [7073ff75] IJulia v1.18.1

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by travigd** [comment]
I think there is an issue with the JS packages rn (the build fails on Travis). I'll (try to) look into this tonight.

**Comment by AnselmJeong** [comment]
Same error here..

Due to undetected WebIO, it is not possible to use `PlotlyJS.jl`

![image](https://user-images.githubusercontent.com/1776524/60767978-4ddb5a00-a0fa-11e9-9f28-581c8a0f3c36.png)

I've added Pkg.add("IJulia"), Pkg.add("WebIO")
I've also installed jupyter labextension by issuing the following command in Julia REPL

```
using WebIO, IJulia
WebIO.install_jupyter_labextension()
```

In the command prompt, the output of `jupyter labextension list` is as follows:
```
JupyterLab v0.35.4
Known labextensions:
   app dir: c:\Users\anselm\Anaconda3\share\jupyter\lab
        @webio/jupyter-lab-provider v0.8.3 enabled  ok*

   local extensions:
        @webio/jupyter-lab-provider: C:\Users\anselm\.julia\packages\WebIO\9qsL8\packages\jupyter-lab-provider

   linked packages:
        @webio/webio: C:\Users\anselm\.julia\packages\WebIO\9qsL8\packages\webio
```

 
```
 julia> versioninfo()
 Julia Version 1.1.1
 Commit 55e36cc308 (2019-05-16 04:10 UTC)
 Platform Info:
   OS: Windows (x86_64-w64-mingw32)
   CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
   WORD_SIZE: 64
   LIBM: libopenlibm
   LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
 
   [7073ff75] IJulia v1.18.1
   [c601a237] Interact v0.10.2
   [47be7bcc] ORCA v0.2.1
   [f0f68f2c] PlotlyJS v0.12.5
   [91a5bcdd] Plots v0.25.3
   [0f1e0344] WebIO v0.8.6
```

I hope someone give me a hint...

**Comment by AnselmJeong** [comment]
Curiously, the above report by @AshtonSBradley  did not raise any issue here...

![image](https://user-images.githubusercontent.com/1776524/60768010-e70a7080-a0fa-11e9-92bc-60ccf2455015.png)

**Comment by AshtonSBradley** [comment]
When I try to install the labextension I get

```julia
julia> using WebIO, IJulia

julia> WebIO.install_jupyter_labextension()
ERROR: IOError: could not spawn `/usr/local/bin/jupyter labextension link --no-build /Users/abradley/.julia/packages/WebIO/9qsL8/packages/webio`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:400
 [2] #505 at ./process.jl:413 [inlined]
 [3] setup_stdios(::getfield(Base, Symbol("##505#506")){Cmd}, ::Array{Any,1}) at ./process.jl:497
 [4] _spawn at ./process.jl:412 [inlined]
 [5] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:725
 [6] run at ./process.jl:724 [inlined]
 [7] install_jupyter_labextension(::Cmd) at /Users/abradley/.julia/packages/WebIO/9qsL8/deps/jupyter.jl:132
 [8] install_jupyter_labextension() at /Users/abradley/.julia/packages/WebIO/9qsL8/deps/jupyter.jl:131
 [9] top-level scope at none:0
```

**Comment by AshtonSBradley** [comment]
@travigd Seems like `WebIO` is looking for a user install, but jupyter in `IJulia` uses a local install by default, which is what I am using on my system. How do I tell `WebIO` to use the containerised jupyter? Or should I be using a user install instead?

**Comment by travigd** [comment]
I'm working on some things to try to fix it right now (see #319).

For now, this should work: `~/.julia/conda/3/bin/jupyter-labextension inst
all @webio/jupyter-lab-provider` (assuming Mac/Linux).

**Comment by AshtonSBradley** [comment]
works Julia 1.1!  (not 1.0)

**Comment by travigd** [comment]
Should be closed by #319.

**Comment by fm444fm** [comment]
I fought with this issue for quite some time. Finally solved it with:
`julia> using WebIO
julia> WebIO.install_jupyter_labextension()`

**Comment by travigd** [comment]
Glad it worked! WebIO defaults to the first Jupyter in the path (though you can change this by passing in the path to the executable as the first argument) and if it can't find any, it uses the one installed by Conda.jl (as part of IJulia, usually). We're working on documentation to make things as easy as possible too.

**Comment by AshtonSBradley** [comment]
Ok. Fresh install on MacOS Mojave, with `]add WebIO#master` `WebIO.install_jupyter_labextension()`, `WebIO.install_jupyter_nbextension()`, rebuild `IJulia`and letting it install its own `conda`. I get `WebIO not detected`.

**Comment by travigd** [comment]
How do you launch Jupyter? What does `which jupyter` output?

**Comment by AshtonSBradley** [comment]
`using IJulia; @async jupyterlab()`. `which jupyter` returns nothing

**Comment by travigd** [comment]
That error message also needs to be updated because it's not done automagically anymore.

Can you include the output of
```julia
run(`$(WebIO.find_jupyter_cmd()) labextension list`)
run(`$(WebIO.find_jupyter_cmd()) nbextension list`)
```

as well as the output from the `install_jupyter_{lab,nb}extension` methods?

**Comment by AshtonSBradley** [comment]
```julia
julia> using WebIO

julia> run(`$(WebIO.find_jupyter_cmd()) labextension list`)
JupyterLab v1.0.2
Known labextensions:
   app dir: /Users/abradley/.julia/conda/3/share/jupyter/lab
        @webio/jupyter-lab-provider v0.8.8  enabled  OK
Process(`/Users/abradley/.julia/conda/3/bin/jupyter labextension list`, ProcessExited(0))

julia> run(`$(WebIO.find_jupyter_cmd()) nbextension list`)
Known nbextensions:
  config dir: /Users/abradley/.jupyter/nbconfig
    notebook section
      webio-jupyter-notebook  enabled 
      - Validating: OK
Process(`/Users/abradley/.julia/conda/3/bin/jupyter nbextension list`, ProcessExited(0))

julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `/Users/abradley/.julia/conda/3/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in /Users/abradley/.julia/conda/3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
Process(`/Users/abradley/.julia/conda/3/bin/jupyter lab build`, ProcessExited(0))

julia> WebIO.install_jupyter_nbextension()
[ Info: Installing Jupyter WebIO extension...
Up to date: /Users/abradley/Library/Jupyter/nbextensions/webio-jupyter-notebook.js

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable <the entry point> --user
    
Enabling notebook extension webio-jupyter-notebook...
      - Validating: OK
Process(`/Users/abradley/.julia/conda/3/bin/jupyter nbextension enable --user webio-jupyter-notebook`, ProcessExited(0))
```

**Comment by travigd** [comment]
Have you refreshed the window and/or restarted Jupyter? Does the toy example that you opened this issue with work?

How about `dom"p"("hello")`?

**Comment by AshtonSBradley** [comment]
restarting jupyterlab gives
<img width="939" alt="Screen Shot 2019-07-29 at 1 05 08 PM" src="https://user-images.githubusercontent.com/24194258/62015642-8c4bcc80-b201-11e9-92ae-8f6526b256cd.png">

**Comment by vilim** [comment]
I have this issue in JupyterLab 1.0

It is possible to install the jupyter lab provider extension, however WebIO claims afterwards:
`WebIO not detected` when trying e.g. node(:div, "Hello World")

I tried uninstalling everything, running jupyter lab clean, and running WebIO.install_jupyter_serverextension and WebIO.install_jupyter_labextension and verifying the jupyter location is correct. There are no errors in the JavaScript browser console, and `jupyter labextension list` shows the extension as installed on the correct version (0.8.8)

**Comment by travigd** [comment]
I can reproduce this. This is likely related to changes in the latest version of WebIO. Will debug.

**Comment by AshtonSBradley** [comment]
I'm getting an error on master when trying `WebIO.install_jupyterlabextension()`
```
julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `/Users/abradley/.julia/conda/3/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in /Users/abradley/.julia/conda/3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/qy/yrp8ty0d77sd4ghs1sxdwt0w0000gp/T/jupyterlab-debug-mjiqnuvm.log
ERROR: failed process: Process(`/Users/abradley/.julia/conda/3/bin/jupyter lab build`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error at ./process.jl:785 [inlined]
 [2] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
 [3] run at ./process.jl:724 [inlined]
 [4] #install_jupyter_labextension#65(::Bool, ::Bool, ::Function, ::Nothing) at /Users/abradley/.julia/packages/WebIO/r6A67/deps/jupyter.jl:154
 [5] install_jupyter_labextension at /Users/abradley/.julia/packages/WebIO/r6A67/deps/jupyter.jl:137 [inlined] (repeats 2 times)
 [6] top-level scope at none:0
```

**Comment by travigd** [comment]
What a terribly unhelpful log message:
> [LabBuildApp] RuntimeError: JupyterLab failed to build

Can you make sure you run
```
export PATH="/Users/abradley/.julia/conda/3/bin:$PATH"
jupyter labextension unlink @webio/webio
jupyter labextension uninstall @webio/jupyter-lab-provider
```
(the `unlink` might error if `@webio/webio` is not installed but it's fine if it does) and the retry installing?

**Comment by AshtonSBradley** [comment]
Same result (also rebuild WebIO, Julia, Interact just to be sure)
<img width="787" alt="Screen Shot 2019-08-02 at 3 53 40 PM" src="https://user-images.githubusercontent.com/24194258/62343164-cee11200-b53d-11e9-8c43-7e1a5d4bf0f5.png">
<img width="760" alt="Screen Shot 2019-08-02 at 3 54 13 PM" src="https://user-images.githubusercontent.com/24194258/62343170-d0aad580-b53d-11e9-91d9-bdcc3be9b3b2.png">
<img width="807" alt="Screen Shot 2019-08-02 at 3 53 16 PM" src="https://user-images.githubusercontent.com/24194258/62343175-d2749900-b53d-11e9-8dbe-23fec5d63ab8.png">

**Comment by AshtonSBradley** [comment]
```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc (2019-05-16 04:10 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by Masacroso** [comment]
I installed jupyter lab extension for WebIO but with an error (see bottom). What I did was calling `julia.exe` from an anaconda prompt in windows 10 and after calling ùsing WebIO` and `WebIO.install_jupyter_labextension()`. However, testing a plot in jupyterlab with PlotlyJS it just shown an empty cell. There is no error (not "webio not detected" this time), just an empty cell.

When installing the lab extension of webio this error appeared:
`julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `'C:\Users\p5b\Anaconda3\Scripts\jupyter.exe'`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  D:\temp\jupyterlab-debug-ifmmargl.log
Uninstalling @webio/jupyter-lab-provider from C:\Users\p5b\Anaconda3\share\jupyter\lab\extensions
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in C:\Users\p5b\Anaconda3\share\jupyter\lab
[LabBuildApp] Building jupyterlab assets
Process(`'C:\Users\p5b\Anaconda3\Scripts\jupyter.exe' lab build`, ProcessExited(0))`

and the log file says:

`Traceback (most recent call last):

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 152, in run_task
    for arg in self.extra_args

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 152, in <listcomp>
    for arg in self.extra_args

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 441, in unlink_package
    return handler.unlink_package(package)

  File "C:\Users\p5b\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 849, in unlink_package
    raise ValueError('No linked package for %s' % path)

ValueError: No linked package for @webio/webio

Exiting application: jupyter`

Also: calling for `jupyter labextension list` it says that the extension is ok, that is
` C:\Users\p5b\AppData\Local\Julia-1.1.1\bin>jupyter labextension list
JupyterLab v1.0.2
Known labextensions:
   app dir: C:\Users\p5b\Anaconda3\share\jupyter\lab
        @webio/jupyter-lab-provider v0.8.9 enabled  ok`

To complete, Im using this packages in Julia:
`[c52e3926] Atom v0.8.8
  [6e4b80f9] BenchmarkTools v0.4.2
  [ad839575] Blink v0.12.0
  [336ed68f] CSV v0.5.9
  [5ae59095] Colors v0.9.5
  [a93c6f00] DataFrames v0.19.1
  [6e83dbb3] Discretizers v3.0.1
  [31c24e10] Distributions v0.21.1
  [28b8d3ca] GR v0.41.0
  [f67ccb44] HDF5 v0.12.0
  [7073ff75] IJulia v1.19.0
  [c601a237] Interact v0.10.2
  [a98d9a8b] Interpolations v0.12.2
  [033835bb] JLD2 v0.1.2
  [e5e0dc1b] Juno v0.7.0
  [5ab0869b] KernelDensity v0.5.1
  [b964fa9f] LaTeXStrings v1.0.3
  [ee78f7c6] Makie v0.9.4
  [47be7bcc] ORCA v0.2.1
  [3b7a836e] PGFPlots v3.1.3
  [8314cec4] PGFPlotsX v1.1.0
  [f0f68f2c] PlotlyJS v0.12.5
  [91a5bcdd] Plots v0.26.0
  [d330b81b] PyPlot v2.8.1
  [6f49c342] RCall v0.13.3
  [ce6b1742] RDatasets v0.6.3
  [e6cf234a] RandomNumbers v1.3.0
  [2913bbd2] StatsBase v0.32.0
  [0f1e0344] WebIO v0.8.9`

**Comment by travigd** [comment]
Unfortunately I can't reproduce this. I suspect you might be infected by the previous "bad" (i.e. not-working/buggy) WebIO jupyterlab extension.

Can you try nuking conda and see if that fixes things?
```julia
run(`rm -rf ~/.julia/dev/conda`)
using Pkg
Pkg.build("Conda")
using IJulia, WebIO
WebIO.install_jupyter_labextension()
jupyterlab()
```

**Comment by AshtonSBradley** [comment]
ok, I have highly system dependent results for this one:

MacOS Mojave 10.14.6
It ran without error, and no longer complains about WebIO not detected. However, while manipulate worked the first time, on subsequent calls (fresh reload of jupyterlab), the sliders don't update

MacOS High Sierra 10.13.6
This one hits an error
<img width="847" alt="Screen Shot 2019-08-06 at 1 29 37 PM" src="https://user-images.githubusercontent.com/24194258/62504975-ddd20800-b84e-11e9-8d4d-35591a99600d.png">



MacOS Mojave 10.14.5
hits a similar error at a different point
<img width="690" alt="Screen Shot 2019-08-06 at 1 33 03 PM" src="https://user-images.githubusercontent.com/24194258/62504962-d01c8280-b84e-11e9-91cd-75296d1ef45e.png">

**Comment by travigd** [comment]
The first one is (probably) because you have Jupyter notebook installed through pip or homebrew. You can specify force_conda_jupyter to make WebIO use the one installed by IJulia (assuming that's how you launch jupyterlab).

The second one will require you to upgrade jupyterlab. You should be able to `Conda.add("jupyterlab")` I believe.

There seem to be some issues with jupyterlab ATM concerning the initial render. Usually refreshing makes things work.

**Comment by AshtonSBradley** [comment]
how do I supply the `force_conda_jupyter` option?

**Comment by travigd** [comment]
WebIO uses the first `jupyter` executable on your system, which, in the first case, is `/usr/local/bin/jupyter`. So there seems to be **some** Jupyter installation there. To force using the conda installation:
```julia
WebIO.install_jupyter_labextension(; force_conda_jupyter=true)
```

I don't have a fix for the second other than just "refresh until it works." Hopefully I'll have some time to look into that soon.

**Comment by AshtonSBradley** [comment]
Checking the third one using this gives a slightly different error
```julia
shell> rm -rf ~/.julia/dev/conda

(v1.1) pkg> build Conda
  Building Conda → `~/.julia/packages/Conda/kLXeC/deps/build.log`

julia> using IJulia, WebIO

julia> WebIO.install_jupyter_labextension(;force_conda_jupyter=true)
[ Info: Using default Jupyter executable at `/Users/abradley/.julia/conda/3/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.

Errored, use --debug for full output:
ValueError: No linked package for @webio/webio
Node v12.5.0

No labextension named "@webio/jupyter-lab-provider" installed
Node v12.5.0

> /usr/local/bin/npm pack @webio/jupyter-lab-provider@0.8.9
npm notice 
npm notice 📦  @webio/jupyter-lab-provider@0.8.9
npm notice === Tarball Contents === 
npm notice 16.6kB dist/labextension.js
npm notice 957B   package.json        
npm notice 438B   README.md           
npm notice === Tarball Details === 
npm notice name:          @webio/jupyter-lab-provider             
npm notice version:       0.8.9                                   
npm notice filename:      webio-jupyter-lab-provider-0.8.9.tgz    
npm notice package size:  5.3 kB                                  
npm notice unpacked size: 18.0 kB                                 
npm notice shasum:        6515884136f4969862ea1184ad5f32aee4413178
npm notice integrity:     sha512-x3N+WghI7hSGR[...]0pQeyr/awc6MA==
npm notice total files:   3                                       
npm notice 
webio-jupyter-lab-provider-0.8.9.tgz

Errored, use --debug for full output:
ValueError: 
"@webio/jupyter-lab-provider@0.8.9" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.1 <2.0.0   @jupyterlab/application
>=0.19.1 <0.20.0        >=1.0.1 <2.0.0   @jupyterlab/docmanager
>=0.19.2 <0.20.0        >=1.0.1 <2.0.0   @jupyterlab/notebook
>=0.19.1 <0.20.0        >=1.0.1 <2.0.0   @jupyterlab/rendermime
>=3.2.1 <4.0.0          >=4.0.1 <5.0.0   @jupyterlab/services
ERROR: failed process: Process(`/Users/abradley/.julia/conda/3/bin/jupyter labextension install --no-build @webio/jupyter-lab-provider@0.8.9`, ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:785 [inlined]
 [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
 [4] run at ./process.jl:724 [inlined]
 [5] #install_jupyter_labextension#66(::Bool, ::Bool, ::Function, ::Nothing) at /Users/abradley/.julia/packages/WebIO/n3Ii6/deps/jupyter.jl:159
 [6] #install_jupyter_labextension at ./none:0 [inlined] (repeats 2 times)
 [7] top-level scope at none:0
```

**Comment by AshtonSBradley** [comment]
On the third one (macOS Mojave 10.14.6) I no longer get a major error after nuking `Conda`, but I get this 
```
julia> WebIO.install_jupyter_labextension(;force_conda_jupyter=true)
[ Info: Using default Jupyter executable at `/Users/abradley/.julia/conda/3/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /var/folders/qy/yrp8ty0d77sd4ghs1sxdwt0w0000gp/T/jupyterlab-debug-4u7r_m1b.log
Uninstalling @webio/jupyter-lab-provider from /Users/abradley/.julia/conda/3/share/jupyter/lab/extensions
[LabBuildApp] JupyterLab 1.0.2
[LabBuildApp] Building in /Users/abradley/.julia/conda/3/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
Process(`/Users/abradley/.julia/conda/3/bin/jupyter lab build`, ProcessExited(0))
```
Then the sliders come appear (WebIO not detected is no longer the issue), but again, they don't update when slid ...

**Comment by jzazo** [comment]
I have the same problem shown in the message above on Ubuntu 18.04.
I have nuked Conda.jl and reinstalled, but I keep getting the same message.
I do have nodejs and npm installed: 
```
$ node -v
v10.13.0
$ npm -v
6.4.1
```

Anyway to fix this problem? Thank you.

**Comment by AshtonSBradley** [comment]
@jzazo did you ever get this working?

**Comment by jzazo** [comment]
Well, I was using ECharts.jl to plot some figures and I could not get it to work on Jupyter nor Atom. However it did work using Blink.jl on terminal, and that sufficed to me. Sorry I cannot help, it didn't work for me.

**Comment by kjfergu** [comment]
I seem to have made some progress on this, though I'm running Jupyter Lab in a docker container on Debian.

For me, the reason none of this was working (Specifically that WebIO couldn't be found) was because I was mounting/using a custom Jupyter config file. It turns out, during the container build, `WebIO` correctly finds and installs itself, but it also adds a few lines on to the end of `~/.jupyter/jupyter_notebook_config.py` which state where to find WebIO and its components. By using a custom, runtime-added config file this was being overwritten and so WebIO couldn't be found because my host config file didn't contain the bits needed.

What I've had to do is edit the `Dockerfile` to copy my config files over during build time, *before* WebIO is installed. This may not be ideal from a "how docker is meant to be used" viewpoint, but it does work.

As a note, I do still get the `ValueError: No linked package for @webio/webio` message during build, but the widgets do still work.

**Comment by kjfergu** [comment]
I should also add the output of `jupyter labextension list`

```
jovyan@0744d1c35e75:~$ which jupyter
/opt/conda/bin/jupyter
jovyan@0744d1c35e75:~$ jupyter labextension list
JupyterLab v1.2.1
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @webio/jupyter-lab-provider v0.8.13  enabled  OK
```

**Comment by shashi** [comment]
> This may not be ideal from a "how docker is meant to be used" viewpoint

Haha what's that?

Yeah this situation sounds a bit out of our control. Although running the install command after your Dockerfile is done setting up (like at the very end) should work too.

**Comment by kjfergu** [comment]
My thought in posting was less about Docker (because obviously that's not WebIO's problem :P) but more sharing what I found was the hang up. Maybe some of the people for whom this isn't working aren't having the right lines added to their Jupyter Config or perhaps they're overwriting the one created by the WebIO installation procedure without realizing it?

**Comment by HuascarOk** [comment]
Hello, I'd like to share with everyone the solution that helped me get out of this problem of not being able to use Interact because of the said error: **WebIO not detected in jupyterlab**

After All my troubleshooting, removing and reinstalling Julia, IJulia, Interact and etc, what helped me was as simple as running from "Anaconda PowerShell Prompt (3)" the next code:

`pip install --user jupyterlab`

**NOTE**: It doesn't matters if you have it already installed from IJulia, I saw no conflict at the time of using this command.
After that, Jupyter started working as expected.
And, btw, I saw some people complaining about the NodeJS package, and I'd like to add that everyone's able to download It using Pkg, just the same way almost everyone of us got IJulia.

This worked on my case, but I'm not 100% sure that it'll do the same in every case.

**Comment by Ooooscar** [comment]
May I ask if anyone has found a stable solution to this?

I'm on macOS 11.0.1. `Interact` does not work on Jupyter notebook: (this screenshot is taken from Visual Studio Code)

<img width="850" alt="Screen Shot 2022-02-19 at 19 07 09" src="https://user-images.githubusercontent.com/70126513/154813465-4a3a6995-d64a-4646-945a-d4ba9d7c2ce4.png">

But it seems to work fine in command line:

<img width="561" alt="Screen Shot 2022-02-19 at 19 03 39" src="https://user-images.githubusercontent.com/70126513/154813472-ee73d17c-2061-42b7-825f-28cbee421924.png">

**Comment by brunocastroibarburu94** [comment]
Can confirm, both Interact.jl and PlotlyJS.jl have the same problem in Windows and Linux. I have been trying for 2 days to sort it :/ 

It would be nice if documentation could be expanded a little and to include a simple test to debug what may be going on with WebIO and Juypyterlab detecting it.

**Comment by AshtonSBradley** [comment]
I know of no solution. I found this so disheartening when dealing with large student groups that I gave up on jupyterlab and moved to Pluto several years ago. For me this proven a highly robust solution to the problem.

**Comment by ctbaum** [comment]
I don't know if this helps debugging this issue but on brand new systemwide installation of jupyterlab via `python3 -m pip install webio_jupyter_extension` and `python3 -m jupyterlab` as recommended on [IJulia](https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/) docs, the following traceback is thrown when running `jupyter lab`

```python
The module 'jupyter_nbextensions_configurator' could not be found (No module named 'jupyter_nbextensions_configurator'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 322, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 186, in __init__
        self._load_metadata()
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 201, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyter_nbextensions_configurator' could not be found (No module named 'jupyter_nbextensions_configurator'). Are you sure the extension is installed?
[W 2023-12-04 22:59:20.748 ServerApp] webio_jupyter_extension.serverextension | error adding extension (enabled: True): The module 'webio_jupyter_extension.serverextension' could not be found (No module named 'notebook'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 322, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 186, in __init__
        self._load_metadata()
      File "/Users/ctl/.pyenv/versions/3.10.9/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 201, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'webio_jupyter_extension.serverextension' could not be found (No module named 'notebook'). Are you sure the extension is installed?
[I 2023-12-04 22:59:20.748 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-12-04 22:59:20.774 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-12-04 22:59:20.775 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-12-04 22:59:20.776 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-12-04 22:59:20.778 LabApp] JupyterLab extension loaded from /Users/ctl/.pyenv/versions/3.10.9/lib/py
```
Also, I don't get WebIO not detected -although I do if jupyter runs within vscode-
<img width="325" alt="image" src="https://github.com/JuliaGizmos/WebIO.jl/assets/84703650/f2b58fc2-c984-4178-8e52-ffec48662366">
I simply don't get the widgets.
Also, for completeness, take a look at the following:
<img width="912" alt="image" src="https://github.com/JuliaGizmos/WebIO.jl/assets/84703650/ed8b2cdc-9af4-480b-a5cb-712a9980fe9f">
I cannot find a higher version though.

**Comment by zsunberg** [comment]
@ctrebbau did you end up fixing this or finding an alternative? I am at the same place and a fear that I may just have to abandon my old notebooks :(
