### ISSUE TITLE
WebIO installation failure

### ISSUE THREAD

**Issue by ea42gh** [JuliaGizmos/WebIO.jl#386]
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
Trying to install webio for jupyterlab, I get
```
julia> using WebIO

julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `/usr/local/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /tmp/jupyterlab-debug-mrse6c8d.log
No labextension named "@webio/jupyter-lab-provider" installed
An error occured.
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter/lab/extensions/webio-jupyter-lab-provider-0.8.13.tgz'
See the log file for details:  /tmp/jupyterlab-debug-t9j2yc6f.log
ERROR: failed process: Process(`/usr/local/bin/jupyter labextension install --no-build @webio/jupyter-lab-provider@0.8.13`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at ./process.jl:525 [inlined]
 [2] #run#565(::Bool, ::typeof(run), ::Cmd) at ./process.jl:440
 [3] run at ./process.jl:438 [inlined]
 [4] #install_jupyter_labextension#67(::Nothing, ::Nothing, ::Bool, ::typeof(WebIO.install_jupyter_labextension), ::Nothing) at /home/user/.julia/packages/WebIO/2nnB1/deps/jupyter.jl:216
 [5] install_jupyter_labextension(::Nothing) at /home/user/.julia/packages/WebIO/2nnB1/deps/jupyter.jl:196 (repeats 2 times)
 [6] top-level scope at REPL[2]:1

julia> 
> cat /tmp/jupyterlab-debug-mrse6c8d.log
Yarn configuration loaded.
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 210, in run_task
    for arg in self.extra_args

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 210, in <listcomp>
    for arg in self.extra_args

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 535, in unlink_package
    return handler.unlink_package(package)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 955, in unlink_package
    raise ValueError('No linked package for %s' % path)

ValueError: No linked package for @webio/webio
```

**Comment by ea42gh** [comment]
Using su julia, i get
```
julia> WebIO.install_jupyter_labextension()
[ Info: Using default Jupyter executable at `/usr/local/bin/jupyter`; to use a different executable, see the documentation by running `?WebIO.install_jupyter_labextension`.
An error occured.
ValueError: No linked package for @webio/webio
See the log file for details:  /tmp/jupyterlab-debug-ptxmyynw.log
No labextension named "@webio/jupyter-lab-provider" installed
```

**Comment by travigd** [comment]
The `ValueError: No linked package for @webio/webio` is harmless.

The installation seems to have succeeded when using `su`.

**Comment by ea42gh** [comment]
it did not show up in `jupyter labextension list`
I commented out the throw error statement,
at which point the installation appeared to succeed.

An lJulia manipulate statement succeded last night.
Today, with no change in the system I am aware of,
it fails....

**Comment by ea42gh** [comment]
One day later, with no known change, this fails again:
I have `@webio/jupyter-lab-provider v0.8.13  enabled  OK` for jupyter lab.
Creating a slider works. Attempting to move the slider results in
```
Uncaught (in promise) Error: Cannot send
    at a.send (comm.js:112)
    at e.sendCallback (labextension.js:276)
    at e.<anonymous> (WebIO.js:292)
    at l (WebIO.js:43)
    at Object.next (WebIO.js:24)
    at o (WebIO.js:15)
```
in both chromium and firefox.
Any suggestions as to what I could try to fix this?

**Comment by ea42gh** [comment]
Weirder:
* I reloaded the webpage in firefox: the slider now updates the display as expected
* Next I restarted the python kernel: the slider no longer updates the display
* reload the page and reexecute the cell generating the slider and display: the slider now updates the display as expected
-----------------------------------------------------------
switch to chromium
* reexecute the cell generating the slider and display:  the slider now updates the display as expected
* restart the python kernel and reexecute the cell: fails
* reload the jupyter page and reexecute the cell: succeeds
?!?!?!?!?!?!?

**Comment by AshtonSBradley** [comment]
same here... its been like this for ages... I know there are limited resources, but I am having to abandon interact because if I use it in lectures or teaching material, and recommend it to a student, then I have to debug _another_ instance of WebIO. Please fix installation bugs and automate it across platforms, this is killing interactive julia. Please view this as a top priority for dev time. IMO it needs to install flawlessly, and _just work_, before any other features are developed
