### ISSUE TITLE
install_jupyter_nbextension() fails

### ISSUE THREAD

**Issue by yha** [JuliaGizmos/WebIO.jl#393]
## The bug

```
julia> WebIO.install_jupyter_nbextension()
┌ Info: Installing Jupyter WebIO extension...
└   cmd = setenv(`'C:\Users\sternlab\.julia\conda\3\Scripts\jupyter.exe' nbextension install --user 'C:\Users\sternlab\.julia\packages\WebIO\2nnB1\deps\bundles\webio-jupyter-notebook.js'`,["PATH=C:\\Users\\sternlab\\.julia\\conda\\3\\Scripts:C:\\Program Files\\AdoptOpenJDK\\jre-8.0.212.03-hotspot\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\MATLAB\\R2019a\\bin;C:\\Program Files (x86)\\MATLAB\\MATLAB Compiler Runtime\\v710\\runtime\\win32;C:\\Program Files (x86)\\celltool\\;C:\\Users\\sternlab\\AppData\\Local\\Microsoft\\WindowsApps;C:\\texlive\\2019\\bin\\win32;C:\\Users\\sternlab\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\sternlab\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\sternlab\\bin\\node-v10.16.0-win-x64;C:\\Users\\sternlab\\AppData\\Local\\atom\\bin;C:\\Users\\sternlab\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\sternlab\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\sternlab\\AppData\\Local\\LyX 2.3\\Perl\\bin", "USERDOMAIN_ROAMINGPROFILE=STAFF", "HOMEPATH=\\Users\\sternlab", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "SYSTEMROOT=C:\\WINDOWS", "APPDATA=C:\\Users\\sternlab\\AppData\\Roaming", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "PROGRAMDATA=C:\\ProgramData"  …  "PROGRAMFILES(X86)=C:\\Program Files (x86)", "OPENBLAS_NUM_THREADS=8", "PROGRAMFILES=C:\\Program Files", "LOGONSERVER=\\\\STAFF-DC1", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FPS_BROWSER_USER_PROFILE_STRING=Default", "SYSTEMDRIVE=C:", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"])
Error executing Jupyter command 'nbextension': [Errno 'jupyter-nbextension' not found] 2
ERROR: failed process: Process(setenv(`'C:\Users\sternlab\.julia\conda\3\Scripts\jupyter.exe' nbextension install --user 'C:\Users\sternlab\.julia\packages\WebIO\2nnB1\deps\bundles\webio-jupyter-notebook.js'`,["PATH=C:\\Users\\sternlab\\.julia\\conda\\3\\Scripts:C:\\Program Files\\AdoptOpenJDK\\jre-8.0.212.03-hotspot\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\PuTTY\\;C:\\Program Files\\MATLAB\\R2019a\\bin;C:\\Program Files (x86)\\MATLAB\\MATLAB Compiler Runtime\\v710\\runtime\\win32;C:\\Program Files (x86)\\celltool\\;C:\\Users\\sternlab\\AppData\\Local\\Microsoft\\WindowsApps;C:\\texlive\\2019\\bin\\win32;C:\\Users\\sternlab\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\sternlab\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\sternlab\\bin\\node-v10.16.0-win-x64;C:\\Users\\sternlab\\AppData\\Local\\atom\\bin;C:\\Users\\sternlab\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\sternlab\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\sternlab\\AppData\\Local\\LyX 2.3\\Perl\\bin", "USERDOMAIN_ROAMINGPROFILE=STAFF", "HOMEPATH=\\Users\\sternlab", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "SYSTEMROOT=C:\\WINDOWS", "APPDATA=C:\\Users\\sternlab\\AppData\\Roaming", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "PROGRAMDATA=C:\\ProgramData"  …  "PROGRAMFILES(X86)=C:\\Program Files (x86)", "OPENBLAS_NUM_THREADS=8", "PROGRAMFILES=C:\\Program Files", "LOGONSERVER=\\\\STAFF-DC1", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FPS_BROWSER_USER_PROFILE_STRING=Default", "SYSTEMDRIVE=C:", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at .\process.jl:525 [inlined]
 [2] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:440
 [3] run at .\process.jl:438 [inlined]
 [4] #install_jupyter_nbextension#68(::Cmd, ::typeof(WebIO.install_jupyter_nbextension), ::Cmd) at C:\Users\sternlab\.julia\packages\WebIO\2nnB1\deps\jupyter.jl:238
 [5] install_jupyter_nbextension(::Cmd) at C:\Users\sternlab\.julia\packages\WebIO\2nnB1\deps\jupyter.jl:233 (repeats 2 times)
 [6] top-level scope at REPL[5]:1
```

## Context
```
(v1.3) pkg> status WebIO
    Status `C:\Users\sternlab\.julia\environments\v1.3\Project.toml`
  [682c06a0] JSON v0.21.0
  [0f1e0344] WebIO v0.8.13

julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-7940X CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by newptcai** [comment]
Similar problem here
When I tried
```
using WebIO
WebIO.install_jupyter_labextension()
```
I got
```
┌ Info: Installing Jupyter WebIO extension...
│   cmd = `/home/xing/anaconda3/bin/jupyter nbextension install --user /home/xing/.julia/packages/WebIO/2nnB1/deps/bundles/webio-jupyter-notebook.js`
└ @ WebIO /home/xing/.julia/packages/WebIO/2nnB1/deps/jupyter.jl:237
Copying: /home/xing/.julia/packages/WebIO/2nnB1/deps/bundles/webio-jupyter-notebook.js -> /home/xing/.local/share/jupyter/nbextensions/webio-jupyter-notebook.js
Traceback (most recent call last):
  File "/home/xing/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/xing/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/xing/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/xing/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 983, in start
    super(NBExtensionApp, self).start()
  File "/home/xing/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 259, in start
    self.subapp.start()
  File "/home/xing/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 711, in start
    self.install_extensions()
  File "/home/xing/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 690, in install_extensions
    **kwargs
  File "/home/xing/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 194, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/home/xing/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 1041, in _maybe_copy
    shutil.copy2(src, dest)
  File "/home/xing/anaconda3/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/xing/anaconda3/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xing/.julia/packages/WebIO/2nnB1/deps/bundles/webio-jupyter-notebook.js'
```
```
