### ISSUE TITLE
WebIO fails to import Highcharts JS file

### ISSUE THREAD

**Issue by chbian** [JuliaGizmos/WebIO.jl#418]
I tried to import [Highcharts](https://github.com/highcharts/highcharts/) plotting library but got the following error:

```
Uncaught (in promise) 
Array(1)
0: Error: Module https://code.highcharts.com/highcharts.js detected as amd but didn't execute correctly. Instantiating https://code.highcharts.com/highcharts.js Loading https://code.highcharts.com/highcharts.js at /home/user/.juliapro/JuliaPro_v1.4.0-1/packages/WebIO/cOHMI/deps/bundles/webio.bundle.js:1:68691
originalErr: Error: Module https://code.highcharts.com/highcharts.js detected as amd but didn't execute correctly. at /home/user/.juliapro/JuliaPro_v1.4.0-1/packages/WebIO/cOHMI/deps/bundles/webio.bundle.js:1:68691
message: "Module https://code.highcharts.com/highcharts.js detected as amd but didn't execute correctly.↵  Instantiating https://code.highcharts.com/highcharts.js↵  Loading https://code.highcharts.com/highcharts.js"
stack: "Error: Module https://code.highcharts.com/highcharts.js detected as amd but didn't execute correctly.↵    at /home/user/.juliapro/JuliaPro_v1.4.0-1/packages/WebIO/cOHMI/deps/bundles/webio.bundle.js:1:68691"
__proto__: Object
length: 1
__proto__: Array(0)
```

Blink complains "Error: Module https://code.highcharts.com/highcharts.js detected as amd but didn't execute correctly."

I am using JuliaPro 1.4.0 on CentOS 7 with WebIO v0.8.92 and Blink v0.12.2. Below is the Julia code that triggers this error.

```julia
w = Blink.Window();

s = Scope(imports = ["https://code.highcharts.com/highcharts.js"]);

onimport(s, @js function()
	console.log("Highcharts JS loaded.")
end);

body!(w,s)
```

**Comment by shashi** [comment]
Only issue similar to this I found is https://github.com/systemjs/systemjs/issues/1615

which seems to be something to do with TypeScript, but this file is not typescript... @travigd any help?
