### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/WebIO.jl#79]
I am trying to install this to use `InteractNext`. When setting up:

```julia
julia> using WebIO

julia> WebIO.devsetup()
INFO: No packages to install, update or remove
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is installed. You must install peer dependencies yourself.
npm WARN abradley@1.0.0 No description
npm WARN abradley@1.0.0 No repository field.

+ webpack-cli@2.0.13
+ webpack@4.2.0
updated 2 packages in 22.707s
INFO: Removing NodeJS v0.4.0

julia> WebIO.bundlejs(watch=false)
INFO: Installing NodeJS v0.4.0
INFO: Building NodeJS
up to date in 2.58s
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/abradley/.julia/v0.6/WebIO/deps/node_modules/webpack-cli/bin/webpack.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ERROR: LoadError: failed process: Process(`/Users/abradley/.julia/v0.6/NodeJS/deps/bin/node-v8.10.0-darwin-x64/bin/node ../../deps/node_modules/webpack-cli/bin/webpack.js`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 [5] #bundlejs#42(::Bool, ::Function) at /Users/abradley/.julia/v0.6/WebIO/src/devsetup.jl:12
 [6] (::WebIO.#kw##bundlejs)(::Array{Any,1}, ::WebIO.#bundlejs) at ./<missing>:0
while loading /Users/abradley/.julia/v0.6/WebIO/deps/_bundlejs.jl, in expression starting on line 22
```

**Comment by shashi** [comment]
You strictly don't need to run `devsetup` unless you are planning to hack on the JS parts of this package... But we should fix this.

**Comment by rdeits** [comment]
@AshtonSBradley can you see if this is resolved on `master`? 

```julia
Pkg.checkout("WebIO")
using WebIO
# devsetup() is no longer required
WebIO.bundlejs()
```

**Comment by AshtonSBradley** [comment]
After removing, reinstalling, updating, I still get
```julia
julia> Pkg.checkout("WebIO")
INFO: Checking out WebIO master...
ERROR: WebIO is dirty, bailing
Stacktrace:
 [1] (::Base.Pkg.Entry.##16#18{String,String,Bool,Bool})(::Base.LibGit2.GitRepo) at ./pkg/entry.jl:228
 [2] transact(::Base.Pkg.Entry.##16#18{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at ./libgit2/libgit2.jl:882
 [3] with(::Base.Pkg.Entry.##15#17{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:608
 [4] checkout(::String, ::String, ::Bool, ::Bool) at ./pkg/entry.jl:226
 [5] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}})() at ./pkg/dir.jl:36
 [6] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}}, ::String) at ./file.jl:70
 [7] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at ./pkg/dir.jl:36
 [8] #checkout#1(::Bool, ::Bool, ::Function, ::String, ::String) at ./pkg/pkg.jl:188
 [9] checkout(::String) at ./pkg/pkg.jl:188
```

**Comment by rdeits** [comment]
It looks like you have some local untracked changes to WebIO, so the package manager is refusing to update it. If you don't want those changes, you can `cd` to the WebIO folder (probably in `~/.julia/v0.6/WebIO`) and do a `git reset --hard HEAD`. Then you should be able to `Pkg.checkout` successfully.

**Comment by AshtonSBradley** [comment]
great, that fixed it!
