### ISSUE TITLE
IJulia via another machine

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/WebIO.jl#90]
I normally run my notebook server via `jupyter notebook --ip=192.168.128.182`. This allows me to send notebook links to colleagues in my local network, eg. `http://192.168.128.182:8888/notebooks/Test_WebIO.ipynb`.  All the examples from the WebIO.jl README work, but if I run

```julia
using PlotlyWebIO

sc = PlotlyWebIO.scatter(x=[1,2], y=[2,3])
wpl = PlotlyWebIO.WebIOPlot(sc)
wpl.scope
```

I get no output. JS console says `Error: The operation was aborted. Instantiating http://192.168.128.182:8888/pkg/PlotlyJS/plotly-latest.min.js`. And the notebook server in the terminal says:

```
[E 09:47:05.639 NotebookApp] Uncaught exception GET /pkg/PlotlyJS/plotly-latest.min.js (192.168.128.198)
    HTTPServerRequest(protocol='http', host='192.168.128.182:8888', method='GET', uri='/pkg/PlotlyJS/plotly-latest.min.js', version='HTTP/1.1', remote_ip='192.168.128.198', headers={'Host': '192.168.128.182:8888', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0', 'Accept': 'application/x-es-module, */*', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://192.168.128.182:8888/notebooks/advisory_notebooks/Test_WebIO-Copy1.ipynb', 'Origin': 'http://192.168.128.182:8888', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1513, in _execute
        self.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 992, in finish
        self.request.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/httputil.py", line 419, in finish
        self.connection.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/http1connection.py", line 448, in finish
        self._expected_content_remaining)
    tornado.httputil.HTTPOutputError: Tried to write 2343103 bytes less than Content-Length
[E 09:47:05.640 NotebookApp] Cannot send error response after headers written
[E 09:47:05.641 NotebookApp] Uncaught exception GET /pkg/PlotlyWebIO/plotly_webio_bundle.js (192.168.128.198)
    HTTPServerRequest(protocol='http', host='192.168.128.182:8888', method='GET', uri='/pkg/PlotlyWebIO/plotly_webio_bundle.js', version='HTTP/1.1', remote_ip='192.168.128.198', headers={'Host': '192.168.128.182:8888', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0', 'Accept': 'application/x-es-module, */*', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Referer': 'http://192.168.128.182:8888/notebooks/advisory_notebooks/Test_WebIO-Copy1.ipynb', 'Origin': 'http://192.168.128.182:8888', 'Connection': 'keep-alive'})
    Traceback (most recent call last):
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 1513, in _execute
        self.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/web.py", line 992, in finish
        self.request.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/httputil.py", line 419, in finish
        self.connection.finish()
      File "/home/cedric/anaconda3/lib/python3.6/site-packages/tornado/http1connection.py", line 448, in finish
        self._expected_content_remaining)
    tornado.httputil.HTTPOutputError: Tried to write 137408 bytes less than Content-Length
[E 09:47:05.641 NotebookApp] Cannot send error response after headers written
```

FWIW, I'm running the server on a Linux machine, and the client is on Windows.

Any idea what might be wrong? PlotlyWebIO's setup code is [here](https://github.com/sglyon/PlotlyWebIO.jl/blob/master/src/plot_type.jl#L21-L112). 

Might be related to #88. I tried both the latest release, and this morning's latest master.

cc. @sglyon

**Comment by cstjean** [comment]
It turns out to be a problem with how the dependencies are specified. If I use

```julia
    deps = [
        "Plotly" => "https://cdn.plot.ly/plotly-latest.min.js",
        "https://raw.githubusercontent.com/sglyon/PlotlyWebIO.jl/master/assets/plotly_webio_bundle.js"
    ]
```

instead of 

```julia
        "Plotly" => "/pkg/PlotlyJS/plotly-latest.min.js",
        "/pkg/PlotlyWebIO/plotly_webio_bundle.js"
```

then it works. But I assume that using `githubusercontent.com` this way would be against Github's TOS. I don't quite understand the `/pkg/` notation, but presumably it's for fetching Javascript locally? Is that fundamentally incompatible with non-local IJulia notebook usage?

**Comment by rdeits** [comment]
Are you on master? This looks like the same error that #70 was supposed to fix.

**Comment by cstjean** [comment]
Yes, checked it out this morning.

**Comment by rdeits** [comment]
Ok, I still think you're running into #57 . The `/pkg` URLs are handled by a jupyter server extension that gets installed when you `Pkg.build("WebIO")`. Could you please try:

* `Pkg.build("WebIO")`
* Restart the jupyter server on your remote host (that is, restart the whole notebook server, not just the kernel)
* try your plotly example again

It's possible that you have the updated code already but if you haven't restarted jupyter then it may not have taken effect.

**Comment by cstjean** [comment]
Solved! Thank you for your help @rdeits

**Comment by rdeits** [comment]
Woohoo!
